"""initial_schema_with_security_master

Revision ID: 34e097367344
Revises:
Create Date: 2026-04-23 13:19:49.040420

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34e097367344"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_run_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("brief_markdown", sa.Text(), nullable=True),
        sa.Column(
            "raw_response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("s3_raw_uri", sa.String(length=255), nullable=True),
        sa.Column("macro_sentiment", sa.String(length=50), nullable=True),
        sa.Column("sector_rotation", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_run_metadata_celery_task_id"),
        "job_run_metadata",
        ["celery_task_id"],
        unique=False,
    )
    op.create_table(
        "target_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_type", sa.Enum("EQUITY", "MUTUAL_FUND", name="assettype"), nullable=False),
        sa.Column("identifier", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_RESOLUTION", "ACTIVE", "MANUAL_INTERVENTION", "FAILED", name="targetstatus"
            ),
            server_default="PENDING_RESOLUTION",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_target_configs_identifier"), "target_configs", ["identifier"], unique=True
    )
    op.create_table(
        "ai_brief_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_run_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.String(length=50), nullable=False),
        sa.Column("catalyst", sa.Text(), nullable=False),
        sa.Column("actionable_edge", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_run_id"], ["job_run_metadata.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["target_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_brief_results_job_run_id"), "ai_brief_results", ["job_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_brief_results_target_id"), "ai_brief_results", ["target_id"], unique=False
    )
    op.create_table(
        "asset_vendor_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("yfinance_symbol", sa.String(length=50), nullable=True),
        sa.Column("screener_symbol", sa.String(length=50), nullable=True),
        sa.Column("nse_symbol", sa.String(length=50), nullable=True),
        sa.Column("amfi_code", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["target_id"], ["target_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_vendor_mapping_target_id"),
        "asset_vendor_mapping",
        ["target_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_asset_vendor_mapping_target_id"), table_name="asset_vendor_mapping")
    op.drop_table("asset_vendor_mapping")
    op.drop_index(op.f("ix_ai_brief_results_target_id"), table_name="ai_brief_results")
    op.drop_index(op.f("ix_ai_brief_results_job_run_id"), table_name="ai_brief_results")
    op.drop_table("ai_brief_results")
    op.drop_index(op.f("ix_target_configs_identifier"), table_name="target_configs")
    op.drop_table("target_configs")
    op.drop_index(op.f("ix_job_run_metadata_celery_task_id"), table_name="job_run_metadata")
    op.drop_table("job_run_metadata")
    # ### end Alembic commands ###
