"""Initialize database with JSONB and Celery tracking

Revision ID: a0efa443d9ee
Revises:
Create Date: 2026-04-04 12:28:45.617217

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a0efa443d9ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_run_metadata", sa.Column("celery_task_id", sa.String(length=255), nullable=True)
    )
    op.add_column("job_run_metadata", sa.Column("brief_markdown", sa.Text(), nullable=True))
    op.add_column(
        "job_run_metadata",
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_job_run_metadata_celery_task_id"),
        "job_run_metadata",
        ["celery_task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_run_metadata_celery_task_id"), table_name="job_run_metadata")
    op.drop_column("job_run_metadata", "raw_response")
    op.drop_column("job_run_metadata", "brief_markdown")
    op.drop_column("job_run_metadata", "celery_task_id")
    # ### end Alembic commands ###
